  import type { Metadata } from "next";
  import { JetBrains_Mono } from "next/font/google";
  import "./globals.css";
  import { Providers } from "@/componenets/providers";
  const jetbrainsMono = JetBrains_Mono({
    variable: "--font-jetbrains-mono",
    subsets: ["latin"],
  });

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <html lang="en">
        <body className={`${jetbrainsMono.variable} antialiased`}>
          <Providers>
            {" "}
            {/* ✅ WRAP */}
            {children}
          </Providers>
        </body>
      </html>
    );
  }
